export const ADDITIVE_RISK:Record<string,any>={
"e100":{
risk:"moderate",
scorePenalty:5
},
"e101":{
risk:"moderate",
scorePenalty:5
},
"e102":{
risk:"moderate",
scorePenalty:5
},
"e103":{
risk:"moderate",
scorePenalty:5
},
"e104":{
risk:"moderate",
scorePenalty:5
},
"e110":{
risk:"moderate",
scorePenalty:5
},
"e120":{
risk:"moderate",
scorePenalty:5
},
"e122":{
risk:"moderate",
scorePenalty:5
},
"e124":{
risk:"moderate",
scorePenalty:5
},
"e129":{
risk:"moderate",
scorePenalty:5
},
"e131":{
risk:"moderate",
scorePenalty:5
},
"e132":{
risk:"moderate",
scorePenalty:5
},
"e133":{
risk:"moderate",
scorePenalty:5
},
"e140":{
risk:"moderate",
scorePenalty:5
},
"e141":{
risk:"moderate",
scorePenalty:5
},
"e142":{
risk:"moderate",
scorePenalty:5
},
"e150":{
risk:"moderate",
scorePenalty:5
},
"e151":{
risk:"moderate",
scorePenalty:5
},
"e153":{
risk:"moderate",
scorePenalty:5
},
"e160":{
risk:"moderate",
scorePenalty:5
},
"e161":{
risk:"moderate",
scorePenalty:5
},
"e162":{
risk:"moderate",
scorePenalty:5
},
"e163":{
risk:"moderate",
scorePenalty:5
},
"e170":{
risk:"moderate",
scorePenalty:5
},
"e171":{
risk:"moderate",
scorePenalty:5
},
"e172":{
risk:"moderate",
scorePenalty:5
},
"e173":{
risk:"moderate",
scorePenalty:5
},
"e174":{
risk:"moderate",
scorePenalty:5
},
"e175":{
risk:"moderate",
scorePenalty:5
},
"e180":{
risk:"moderate",
scorePenalty:5
},
"bht":{
risk:"moderate",
scorePenalty:5
},
"bha":{
risk:"moderate",
scorePenalty:5
},
"msg":{
risk:"moderate",
scorePenalty:5
},
"monosodium glutamate":{
risk:"moderate",
scorePenalty:5
},
"aspartame":{
risk:"moderate",
scorePenalty:5
},
"acesulfame k":{
risk:"moderate",
scorePenalty:5
},
"sucralose":{
risk:"moderate",
scorePenalty:5
},
"saccharin":{
risk:"moderate",
scorePenalty:5
},
"sodium nitrite":{
risk:"moderate",
scorePenalty:5
},
"sodium nitrate":{
risk:"moderate",
scorePenalty:5
},
"potassium sorbate":{
risk:"moderate",
scorePenalty:5
},
"synthetic_additive_1":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_2":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_3":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_4":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_5":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_6":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_7":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_8":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_9":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_10":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_11":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_12":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_13":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_14":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_15":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_16":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_17":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_18":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_19":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_20":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_21":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_22":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_23":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_24":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_25":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_26":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_27":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_28":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_29":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_30":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_31":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_32":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_33":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_34":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_35":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_36":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_37":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_38":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_39":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_40":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_41":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_42":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_43":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_44":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_45":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_46":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_47":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_48":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_49":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_50":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_51":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_52":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_53":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_54":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_55":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_56":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_57":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_58":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_59":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_60":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_61":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_62":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_63":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_64":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_65":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_66":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_67":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_68":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_69":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_70":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_71":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_72":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_73":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_74":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_75":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_76":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_77":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_78":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_79":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_80":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_81":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_82":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_83":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_84":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_85":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_86":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_87":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_88":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_89":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_90":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_91":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_92":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_93":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_94":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_95":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_96":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_97":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_98":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_99":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_100":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_101":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_102":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_103":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_104":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_105":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_106":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_107":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_108":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_109":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_110":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_111":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_112":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_113":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_114":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_115":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_116":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_117":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_118":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_119":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_120":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_121":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_122":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_123":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_124":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_125":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_126":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_127":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_128":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_129":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_130":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_131":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_132":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_133":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_134":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_135":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_136":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_137":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_138":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_139":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_140":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_141":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_142":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_143":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_144":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_145":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_146":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_147":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_148":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_149":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_150":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_151":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_152":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_153":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_154":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_155":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_156":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_157":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_158":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_159":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_160":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_161":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_162":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_163":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_164":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_165":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_166":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_167":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_168":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_169":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_170":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_171":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_172":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_173":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_174":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_175":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_176":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_177":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_178":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_179":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_180":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_181":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_182":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_183":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_184":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_185":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_186":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_187":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_188":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_189":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_190":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_191":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_192":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_193":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_194":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_195":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_196":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_197":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_198":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_199":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_200":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_201":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_202":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_203":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_204":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_205":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_206":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_207":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_208":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_209":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_210":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_211":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_212":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_213":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_214":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_215":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_216":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_217":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_218":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_219":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_220":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_221":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_222":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_223":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_224":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_225":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_226":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_227":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_228":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_229":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_230":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_231":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_232":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_233":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_234":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_235":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_236":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_237":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_238":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_239":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_240":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_241":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_242":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_243":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_244":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_245":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_246":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_247":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_248":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_249":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_250":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_251":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_252":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_253":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_254":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_255":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_256":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_257":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_258":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_259":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_260":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_261":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_262":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_263":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_264":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_265":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_266":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_267":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_268":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_269":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_270":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_271":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_272":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_273":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_274":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_275":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_276":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_277":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_278":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_279":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_280":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_281":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_282":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_283":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_284":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_285":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_286":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_287":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_288":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_289":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_290":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_291":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_292":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_293":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_294":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_295":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_296":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_297":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_298":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_299":{
risk:"moderate",
scorePenalty:3
},
"synthetic_additive_300":{
risk:"moderate",
scorePenalty:3
},}

