export const INGREDIENT_KNOWLEDGE:Record<string,any>={
"sugar":{benefits:[],risks:[],scorePenalty:0},
"salt":{benefits:[],risks:[],scorePenalty:0},
"water":{benefits:[],risks:[],scorePenalty:0},
"corn starch":{benefits:[],risks:[],scorePenalty:0},
"yeast":{benefits:[],risks:[],scorePenalty:0},
"soy":{benefits:[],risks:[],scorePenalty:0},
"milk":{benefits:[],risks:[],scorePenalty:0},
"egg":{benefits:[],risks:[],scorePenalty:0},
"peanut":{benefits:[],risks:[],scorePenalty:0},
"almond":{benefits:[],risks:[],scorePenalty:0},
"wheat":{benefits:[],risks:[],scorePenalty:0},
"glucose syrup":{benefits:[],risks:[],scorePenalty:0},
"fructose":{benefits:[],risks:[],scorePenalty:0},
"corn syrup":{benefits:[],risks:[],scorePenalty:0},
"citric acid":{benefits:[],risks:[],scorePenalty:0},
"sodium benzoate":{benefits:[],risks:[],scorePenalty:0},
"potassium sorbate":{benefits:[],risks:[],scorePenalty:0},
"ascorbic acid":{benefits:[],risks:[],scorePenalty:0},
"carrageenan":{benefits:[],risks:[],scorePenalty:0},
"lecithin":{benefits:[],risks:[],scorePenalty:0},
"gelatin":{benefits:[],risks:[],scorePenalty:0},
"casein":{benefits:[],risks:[],scorePenalty:0},
"whey":{benefits:[],risks:[],scorePenalty:0},
"maltodextrin":{benefits:[],risks:[],scorePenalty:0},
"xanthan gum":{benefits:[],risks:[],scorePenalty:0},
"guar gum":{benefits:[],risks:[],scorePenalty:0},
"pectin":{benefits:[],risks:[],scorePenalty:0},
"baking soda":{benefits:[],risks:[],scorePenalty:0},
"baking powder":{benefits:[],risks:[],scorePenalty:0},
"vanilla":{benefits:[],risks:[],scorePenalty:0},
"cocoa":{benefits:[],risks:[],scorePenalty:0},
"cocoa butter":{benefits:[],risks:[],scorePenalty:0},
"chocolate":{benefits:[],risks:[],scorePenalty:0},
"coffee":{benefits:[],risks:[],scorePenalty:0},
"tea":{benefits:[],risks:[],scorePenalty:0},
"rice":{benefits:[],risks:[],scorePenalty:0},
"oats":{benefits:[],risks:[],scorePenalty:0},
"barley":{benefits:[],risks:[],scorePenalty:0},
"rye":{benefits:[],risks:[],scorePenalty:0},
"quinoa":{benefits:[],risks:[],scorePenalty:0},
"chia":{benefits:[],risks:[],scorePenalty:0},
"flaxseed":{benefits:[],risks:[],scorePenalty:0},
"canola oil":{benefits:[],risks:[],scorePenalty:0},
"palm oil":{benefits:[],risks:[],scorePenalty:0},
"olive oil":{benefits:[],risks:[],scorePenalty:0},
"sunflower oil":{benefits:[],risks:[],scorePenalty:0},
"sesame oil":{benefits:[],risks:[],scorePenalty:0},
"peanut oil":{benefits:[],risks:[],scorePenalty:0},
"avocado oil":{benefits:[],risks:[],scorePenalty:0},
}





