export const INGREDIENT_DATASET: Record<string, string> = {
  "sodium benzoate": "Preservative used to prevent microbial growth.",
  "citric acid": "Natural acid used for flavor and preservation.",
  "potassium sorbate": "Common food preservative that helps prevent mold growth.",
  "glycerin": "Humectant that retains moisture in skin products.",
  "sodium laureth sulfate": "Surfactant used in shampoos and cleansers.",
  "cocamidopropyl betaine": "Foaming agent derived from coconut oil.",
  "soy lecithin": "Emulsifier used to stabilize food mixtures.",
  "monosodium glutamate": "Flavor enhancer used in many processed foods.",
  "maltodextrin": "Processed carbohydrate used as a thickener or filler.",
  "ascorbic acid": "Vitamin C used as an antioxidant and preservative.",

  "salt": "Common seasoning and preservative. Excess intake may contribute to high blood pressure.",
  "sugar": "Sweetener used for flavor. High intake may contribute to metabolic issues.",
  "high fructose corn syrup": "Processed sweetener commonly used in sauces and packaged foods.",
  "corn syrup": "Liquid sweetener used in processed foods for sweetness and texture.",
  "corn starch": "Starch used as a thickener and stabilizer in packaged foods.",
  "vinegar": "Acidic ingredient used for flavor and preservation.",
  "distilled vinegar": "Refined vinegar commonly used for acidity and preservation.",
  "tomato": "Ingredient naturally associated with lycopene and acidity.",
  "tomato concentrate": "Concentrated tomato ingredient used for flavor and color.",
  "concentrated red tomatoes": "Tomato concentrate used as a base ingredient in sauces and condiments.",
  "onion": "Aromatic vegetable used for flavor in savory foods.",
  "onion powder": "Dehydrated onion used as a seasoning ingredient.",
  "garlic": "Flavoring ingredient commonly used in savory foods.",
  "pepper": "Common spice used for flavor and mild heat.",
  "spice": "General seasoning blend used to improve flavor.",
  "spices": "General seasoning ingredients used to improve flavor.",
  "natural flavoring": "Flavoring blend used to enhance taste; exact composition may not be disclosed.",
  "flavoring": "Added flavor component used to improve taste; exact composition may vary."
};
